name: navigation_action_bar
description: A beautiful modern Navigation Bar along with a Floating Action Bar.
version: 0.0.1
homepage: https://github.com/aseem09/navigation_action_bar

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
